"""Formula catalogue (matplotlib mathtext).  (key, group, tex, explanation) -- '@@' separates lines of one image."""
F = [
 # ---------------- A. Agent & MAS (Bab 3-4)
 ("agent", "A. Agen dan sistem multi-agen", r"$A=\langle G,B,I,M,C,R,P,T\rangle,\qquad s_{t+1}=F(s_t,o_t,a_t)$",
  "G goal, B belief, I intention, M memory, C context, R reasoning, P planning, T tools (Bab 3). s_t keadaan sistem, o_t observasi, a_t aksi, F fungsi transisi lingkungan."),
 ("mas", "A. Agen dan sistem multi-agen", r"$\mathrm{MAS}=\langle \mathcal{A},E,S,O,\mathrm{Act},C,\Phi\rangle,\qquad a_i=\langle G_i,B_i,I_i,M_i,\pi_i\rangle$",
  "A himpunan agen, E lingkungan, S state, O observasi, Act aksi, C komunikasi, Phi aturan interaksi (protokol); pi_i kebijakan keputusan agen i (Bab 4)."),
 ("rational", "A. Agen dan sistem multi-agen", r"$a^{*}=\arg\max_{a}\ U(a\mid s,g,c)\quad \mathrm{s.t.}\quad \mathrm{policy}(a)=1$",
  "Agen rasional memilih aksi dengan utilitas tertinggi U yang tetap memenuhi kebijakan/constraint (budget, compliance, wewenang, batas konsentrasi produsen)."),
 ("autonomy", "A. Agen dan sistem multi-agen", r"$\mathrm{autonomy}=\mathbf{1}\left[\,\mathrm{risk}<\rho\ \wedge\ \mathrm{conf}>\tau\ \wedge\ \mathrm{authority}=1\,\right]$",
  "Aksi otomatis (level 4, delegate) hanya jika risiko < rho, confidence > tau, dan agen berwenang; selain itu perlu persetujuan manusia (level 2), mis. verifikasi DP dan HS confidence rendah."),
 # ---------------- B. Model masalah
 ("obj", "B. Model masalah ekspor konsorsium", r"$J=C_{\mathrm{src}}+C_{\mathrm{frt}}+C_{\mathrm{hold}}+C_{\mathrm{ot}}+C_{\mathrm{human}}+\sum_i\mathrm{Pen}(L_i)$@@$M=\sum_i V_i\,\varphi_i\,(1-\delta_i)\;-\;J$",
  "J biaya total (sourcing, freight, penyimpanan, lembur, sentuhan manusia, penalti). M margin kontribusi: V_i nilai kontrak order i, phi_i fill rate, delta_i diskon shelf-life. Dipakai sebagai fungsi tujuan (Bab 4: service-cost objective)."),
 ("fill", "B. Model masalah ekspor konsorsium", r"$\varphi=\min\left(1,\ \dfrac{\sum_j \mathrm{pass}_j}{Q}\right),\qquad \mathrm{OTIF}=\mathbf{1}\left[L=0\ \wedge\ \varphi\geq 0.98\right]$",
  "phi fill rate (kg lolos QC dibagi kebutuhan Q); OTIF (on-time in-full) bernilai 1 bila kirim tepat waktu dan terisi >= 98%."),
 ("pen", "B. Model masalah ekspor konsorsium", r"$\mathrm{Pen}(d)=0.004\,V\,d+45\,d+0.05\,V\cdot\mathbf{1}[d>10]$",
  "V nilai kontrak (USD), d hari keterlambatan di atas toleransi. 0,4% nilai per hari + 45 USD/hari demurrage/storage + diskon 5% bila L/C basi (d > 10). ASUMSI pemodelan."),
 ("closing", "B. Model masalah ekspor konsorsium", r"$c_j(t)=o_j+7\left\lceil\dfrac{t-o_j}{7}\right\rceil,\quad \mathrm{dep}=c_j+3+7\cdot\mathbf{1}[\mathrm{rolled}],\quad L=\max(0,\ \mathrm{dep}-\mathrm{LSD})$",
  "c_j(t) closing kapal carrier j pertama yang >= t (berlayar mingguan, offset o_j); keberangkatan = closing + 3 hari, +7 hari bila kargo tidak terangkut (roll-over); L keterlambatan terhadap LSD (latest shipment date, toleransi 2 hari)."),
 ("shelf", "B. Model masalah ekspor konsorsium", r"$\mathrm{age}=(\mathrm{dep}-t_{\mathrm{frozen}})+T_{\mathrm{transit}},\qquad \delta=\begin{cases}\end{cases}$", ""),
 # ---------------- C. Sourcing / quota allocation
 ("need", "C. Alokasi kuota ke produsen UMKM (Contract Net)", r"$N_0=Q\,(1+b),\qquad N_k=\left(Q-\sum \mathrm{pass}\right)(1+b_r)$",
  "Kebutuhan awal N_0 = kuantitas Q ditambah buffer over-allocation b = 15% (lindung nilai terhadap gagal kirim dan reject QC); putaran susulan (re-kontrak) N_k menutup kekurangan dengan buffer b_r = 5%."),
 ("offer", "C. Alokasi kuota ke produsen UMKM (Contract Net)", r"$o_j=c_j\,u_j\,W_j,\qquad W_j=\max\left(0,\ t_{\mathrm{need}}-t^{\mathrm{start}}_j-\tau_{\mathrm{lag}}-\tau_{\mathrm{tr}}\right)$",
  "Tawaran produsen j: c_j kapasitas nominal (kg/hari), u_j ketersediaan aktual hari itu (0,55-1: sisa setelah pasar lokal), W_j jendela produksi; tau_lag fermentasi/karbonisasi, tau_tr transport. Pada multi-agen produsen menawar dengan u_j sebenarnya (informasi lokal)."),
 ("central_est", "C. Alokasi kuota ke produsen UMKM (Contract Net)", r"$\hat{o}_j=\hat{c}_j\,\bar{u}\,W_j,\qquad \hat{c}_j=c_j(1+\varepsilon_j),\ \ \varepsilon_j\sim\mathcal{N}(0,0.10^2)$",
  "Estimasi agen tunggal dari registry: c^_j kapasitas hasil onboarding (kedaluwarsa/berderau epsilon_j), u_bar ketersediaan rata-rata (0,775). Selisih o^_j vs o_j menimbulkan over-commit dan putaran susulan."),
 ("score", "C. Alokasi kuota ke produsen UMKM (Contract Net)", r"$s_j=w_p\,(1-\tilde p_j)+w_q\,q_j+w_s\,\tilde o_j,\qquad (w_p,w_q,w_s)=(0.3,\ 0.5,\ 0.2)$",
  "Skor bid: p~_j harga ternormalisasi (0-1), q_j quality score produsen, o~_j kecepatan (tawaran ternormalisasi). Order Agent memberi kuota berurut skor tertinggi: x_j = min(o_j, N_sisa, 0,3 x 1,3 Q); produsen dengan q_j < 0,60 tidak dikontrak."),
 ("qc", "C. Alokasi kuota ke produsen UMKM (Contract Net)", r"$d_j=\min\left(x_j,\ c_j u_j W_j\right),\qquad \mathrm{pass}_j=d_j\,g_j\,f_j\,(1-\mathbf{1}[\mathrm{default}_j])$",
  "d_j kg yang benar-benar dapat dikirim; g_j = yield lolos QC (CV/lab) produsen j + derau; f_j = 1 bila memenuhi grade (0,55 bila order premium dan yield < 0,85); default_j gagal kirim dengan peluang 1 - keandalan."),
 ("qscore", "C. Alokasi kuota ke produsen UMKM (Contract Net)", r"$q_j\leftarrow\lambda\,q_j+(1-\lambda)\,g_j f_j,\qquad \lambda=0.8$",
  "Pembaruan quality score (bentuk trust eksponensial Bab 4): produsen konsisten Grade A memperoleh prioritas kuota berikutnya (insentif kualitas organik); gagal kirim memberi hasil 0."),
 # ---------------- D. Warehouse & carrier
 ("cr", "D. Gudang konsolidasi dan pemilihan carrier", r"$CR_i=\dfrac{d_i-t}{W_i},\qquad \mathrm{ETA}_m=t_0+\dfrac{L_m+w}{v_m}$",
  "Critical ratio: d_i batas tiba di gerbang pelabuhan, t waktu sekarang, W_i sisa beban; CR terkecil dikerjakan dulu. ETA_m tawaran lini gudang m: t_0 waktu mulai, L_m beban antrean, w kerja baru, v_m kecepatan."),
 ("z", "D. Gudang konsolidasi dan pemilihan carrier", r"$z_j=100\left(w_c\,\dfrac{c_{\min}}{c_j}+w_t\,\dfrac{d_{\min}}{d_j}+w_r\,T_j\right),\qquad h_j=g_j\left[\alpha z_j+(1-\alpha)\,100\,(1-p_j)\right]$",
  "Skor hibrida carrier (Bab 3): z_j skor DSS (biaya, keberangkatan, trust T_j; bobot 0,45/0,25/0,30), p_j peluang roll-over dari model ML, g_j gerbang kelayakan (trust >= 0,60 dan berangkat <= LSD), alpha = 0,55."),
 ("expcost", "D. Gudang konsolidasi dan pemilihan carrier", r"$E[\mathrm{cost}_j]=c_j+(1-p_j)\,\mathrm{Pen}_0+p_j\,\mathrm{Pen}_7,\qquad T_j(t+1)=\lambda\,T_j(t)+(1-\lambda)\,q$",
  "Biaya harapan (Pen_0 bila terangkut, Pen_7 bila tergeser 7 hari) dan pembaruan trust carrier: q = 1 bila terangkut, 0,2 bila roll-over. Trusted >= 0,80; conditional 0,60-0,80; blocked < 0,60."),
 ("shelf2", "D. Gudang konsolidasi dan pemilihan carrier", r"$\mathrm{age}=(\mathrm{dep}-t_{\mathrm{frozen}})+T_{\mathrm{transit}},\qquad \mathrm{remain}=45-\mathrm{age}$@@$\delta=0.10\ \text{jika}\ \mathrm{remain}<10,\quad \delta=0.50\ \text{jika}\ \mathrm{remain}<0$",
  "Shelf-life produk perishable (tempe vakum beku, uji tim: 1-2 bulan; dipakai 45 hari): umur saat tiba = waktu tunggu setelah pembekuan + transit; diskon harga delta bila sisa umur < 10 hari."),
 # ---------------- E. ML
 ("cos", "E. Machine learning", r"$\cos(\mathbf{a},\mathbf{b})=\dfrac{\mathbf{a}\cdot\mathbf{b}}{\|\mathbf{a}\|\,\|\mathbf{b}\|},\qquad \mathrm{tfidf}(t,d)=\mathrm{tf}(t,d)\left(\ln\dfrac{1+N}{1+\mathrm{df}(t)}+1\right)$",
  "Kemiripan kosinus vektor TF-IDF deskripsi produk (Compliance Agent, klasifikasi HS). tf frekuensi term t pada dokumen d, N jumlah dokumen latih, df(t) jumlah dokumen berisi t (varian smooth scikit-learn)."),
 ("knn", "E. Machine learning", r"$\mathrm{conf}(y)=\dfrac{\sum_{i\in N_k,\ y_i=y}\cos(x,x_i)}{\sum_{i\in N_k}\cos(x,x_i)}$",
  "k-NN berbobot kosinus (k=5): confidence = porsi bobot tetangga N_k berlabel y. Bila conf < 0,60 keputusan diserahkan ke manusia (selective classification)."),
 ("logit", "E. Machine learning", r"$p=\sigma(z)=\dfrac{1}{1+e^{-z}},\qquad z=b+\mathbf{w}^{\top}\tilde{\mathbf{x}}$@@$\mathcal{L}=-\dfrac{1}{n}\sum_i\left[y_i\ln p_i+(1-y_i)\ln(1-p_i)\right]+\dfrac{\lambda}{2}\|\mathbf{w}\|^2,\qquad \mathbf{w}\leftarrow\mathbf{w}-\eta\,\nabla\mathcal{L}$",
  "Regresi logistik Risk Agent: x~ fitur terstandarisasi (carrier, kongesti, musim puncak, buffer hari, jumlah kontainer), y = 1 bila roll-over, lambda regularisasi L2, eta learning rate."),
 ("truth", "E. Machine learning", r"$\mathrm{logit}\,p_j=b_j+1.8\,\mathrm{cong}+1.1\,\mathrm{peak}-0.3\,\mathrm{buf}$",
  "Proses pembangkit data (kebenaran tersembunyi yang tidak dilihat agen): b_j dasar per carrier, cong kongesti pelabuhan, peak musim puncak, buf selisih hari antara tiba di gerbang dan closing."),
 ("metrics", "E. Machine learning", r"$\mathrm{AUC}=P(s^{+}>s^{-}),\qquad \mathrm{Brier}=\dfrac{1}{n}\sum_i(p_i-y_i)^2,\qquad \hat{\beta}=\dfrac{\sum_t (t-\bar t)(x_t-\bar x)}{\sum_t (t-\bar t)^2}$",
  "AUC peluang skor positif melebihi negatif; Brier kalibrasi probabilitas; beta topi kemiringan tren percept sequence sensor mesin (Bab 2: 55, 60, 64, 72, 80 C: tren naik = risiko kerusakan)."),
 # ---------------- F. RL
 ("q", "F. Reinforcement learning", r"$Q(s,a)\leftarrow Q(s,a)+\alpha\left[r+\gamma\max_{a'}Q(s',a')-Q(s,a)\right]$",
  "Q-learning (Bab 4-5): s = (bucket slack, bucket nilai order, tahap), a in {normal, lembur}, r = -biaya lembur; reward akhir = -penalti. alpha learning rate, gamma discount; eksplorasi epsilon-greedy."),
 # ---------------- G. Coordination
 ("nego", "G. Koordinasi, negosiasi, dan metrik MAS", r"$p_B(t)=p_B^{0}+\left(p_B^{\max}-p_B^{0}\right)\left(\dfrac{t}{T}\right)^{\beta},\qquad x^{*}=\arg\max_{x}\prod_{i}\left[U_i(x)-d_i\right]$",
  "Konsesi bergantung waktu dan Nash bargaining (Bab 4), dipakai Sales Agent: pembeli menaikkan tawaran dari p_B^0 menuju batas p_B^max dalam T ronde; sepakat bila tawaran pembeli >= permintaan penjual; d_i utilitas bila gagal sepakat."),
 ("deal", "G. Koordinasi, negosiasi, dan metrik MAS", r"$P(\mathrm{deal})=P\left(T_{\mathrm{reply}}<T_{\mathrm{patience}}\right)\cdot P\left(v_B\geq f\right),\qquad T_{\mathrm{patience}}\sim\mathrm{Exp}(\mathrm{mean}\ 72\ \mathrm{h})$",
  "Peluang deal (modul eksploratif Sales Agent): balas sebelum kesabaran pembeli habis dan harga reservasi pembeli v_B >= batas bawah penjual f. Distribusi waktu balas adalah ASUMSI."),
 ("speed", "G. Koordinasi, negosiasi, dan metrik MAS", r"$S(n)=\dfrac{T_1}{T_n},\quad \eta(n)=\dfrac{S(n)}{n},\qquad R_{\mathrm{sys}}=1-\prod_i(1-R_i)$",
  "Speedup dan efisiensi paralel; keandalan sistem dengan redundansi (3 agen R=0,9 memberi 0,999). Sumber: Bab 4 sub-bab Skalabilitas."),
 ("comm", "G. Koordinasi, negosiasi, dan metrik MAS", r"$C_{\mathrm{comm}}=\sum_m\left(\dfrac{L_m}{B}+\tau\right),\qquad \mathrm{Jain}(x)=\dfrac{(\sum x_i)^2}{n\sum x_i^2}$",
  "Biaya komunikasi: L ukuran pesan, B bandwidth 8 Mbps, tau latensi 20 ms. Indeks keadilan Jain (1 = merata) dipakai untuk pemerataan kuota antar produsen UMKM (tujuan inklusi ekonomi) dan utilisasi lini gudang."),
 # ---------------- H. Security & mobility
 ("sec", "H. Keamanan, trust, dan mobilitas agen", r"$\sigma=\mathrm{HMAC}_{K}\left(H(m)\right),\qquad \mathrm{accept}\Leftrightarrow \mathrm{nonce}\notin\mathrm{Seen}\ \wedge\ |t_{\mathrm{now}}-t_m|<\Delta\ \wedge\ a\in\mathrm{Cap}_i$",
  "Integritas pesan (tanda tangan HMAC-SHA256), pertahanan replay (nonce + jendela waktu Delta), dan capability check (aksi harus ada pada himpunan wewenang agen)."),
 ("mig", "H. Keamanan, trust, dan mobilitas agen", r"$\mathrm{migrate}\Leftrightarrow T_{\mathrm{host}}\geq\theta_T\ \wedge\ \mathrm{Verify}(\sigma)\ \wedge\ \mathrm{Risk}\leq\theta_R$@@$\mathrm{Score}=0.5\,(1-\mathrm{lat}_{\mathrm{norm}})+0.5\,T_{\mathrm{host}}$",
  "Syarat migrasi Scout Agent (Bab 4-5): trust host >= 0,80, state terverifikasi, risiko <= 0,20. Skor komposit hanya meranking host yang lolos; keamanan adalah constraint keras."),
]
F = [f for f in F if f[0] not in ("shelf",)]
