"""Formula catalogue (matplotlib mathtext).  (key, group, tex, explanation)  -- '@@' separates lines of one image."""
F = [
 # ---------------- A. Agent & MAS (Bab 3-4)
 ("agent", "A. Agen dan sistem multi-agen", r"$A=\langle G,B,I,M,C,R,P,T\rangle,\qquad s_{t+1}=F(s_t,o_t,a_t)$",
  "G goal, B belief, I intention, M memory, C context, R reasoning, P planning, T tools (Bab 3). s_t keadaan sistem, o_t observasi, a_t aksi, F fungsi transisi lingkungan."),
 ("mas", "A. Agen dan sistem multi-agen", r"$\mathrm{MAS}=\langle \mathcal{A},E,S,O,\mathrm{Act},C,\Phi\rangle,\qquad a_i=\langle G_i,B_i,I_i,M_i,\pi_i\rangle$",
  "A himpunan agen, E lingkungan, S state, O observasi, Act aksi, C komunikasi, Phi aturan interaksi (protokol); pi_i kebijakan keputusan agen i (Bab 4)."),
 ("rational", "A. Agen dan sistem multi-agen", r"$a^{*}=\arg\max_{a}\ U(a\mid s,g,c)\quad \mathrm{s.t.}\quad \mathrm{policy}(a)=1$",
  "Agen rasional memilih aksi dengan utilitas tertinggi U yang tetap memenuhi kebijakan/constraint (budget, compliance, wewenang). s state, g goal, c konteks."),
 ("autonomy", "A. Agen dan sistem multi-agen", r"$\mathrm{autonomy}=\mathbf{1}\left[\,\mathrm{risk}<\rho\ \wedge\ \mathrm{conf}>\tau\ \wedge\ \mathrm{authority}=1\,\right]$",
  "Aksi dieksekusi otomatis (level 4, delegate) hanya jika risiko < rho, confidence > tau, dan agen berwenang; selain itu perlu persetujuan manusia (level 2)."),
 # ---------------- B. Problem & logistics
 ("obj", "B. Model masalah ekspor", r"$J=C_{\mathrm{frt}}+C_{\mathrm{hold}}+C_{\mathrm{ot}}+C_{\mathrm{human}}+\sum_{i}\mathrm{Pen}(L_i)$",
  "Biaya total per skenario yang diminimalkan: freight, penyimpanan barang jadi, lembur, biaya sentuhan manusia, dan penalti keterlambatan tiap order i (Bab 4: service-cost objective)."),
 ("pen", "B. Model masalah ekspor", r"$\mathrm{Pen}(d)=0.004\,V\,d+45\,d+0.05\,V\cdot\mathbf{1}[d>10]$",
  "V nilai order (USD), d hari keterlambatan di atas toleransi. 0,4% nilai per hari + 45 USD/hari demurrage/storage + diskon 5% bila L/C basi (d > 10). ASUMSI pemodelan."),
 ("closing", "B. Model masalah ekspor", r"$c_j(t)=o_j+7\left\lceil\dfrac{t-o_j}{7}\right\rceil,\qquad \mathrm{dep}=c_j+3+7\cdot\mathbf{1}[\mathrm{rolled}]$",
  "c_j(t) closing kapal carrier j pertama yang >= t (kapal berangkat mingguan, offset o_j); keberangkatan = closing + 3 hari, +7 hari bila kargo tidak terangkut (roll-over)."),
 ("late", "B. Model masalah ekspor", r"$L=\max\left(0,\ \mathrm{dep}-\mathrm{LSD}\right)$",
  "L keterlambatan; LSD (latest shipment date) = keberangkatan kapal yang dijanjikan + toleransi 2 hari."),
 # ---------------- C. Scheduling
 ("cr", "C. Penjadwalan produksi (Contract Net)", r"$CR_i=\dfrac{d_i-t}{W_i}$",
  "Critical ratio: d_i batas waktu tiba di gerbang pelabuhan, t waktu sekarang, W_i sisa beban kerja. CR terkecil (paling mendesak) dikerjakan lebih dulu."),
 ("eta", "C. Penjadwalan produksi (Contract Net)", r"$\mathrm{ETA}_m=t_0+\dfrac{L_m+w}{v_m}$",
  "Tawaran (bid) agen mesin m: t_0 waktu mulai (setelah perbaikan bila mesin rusak/terindikasi rusak), L_m beban antrean, w kerja baru, v_m kecepatan mesin."),
 ("bidscore", "C. Penjadwalan produksi (Contract Net)", r"$\mathrm{score}_i=0.5\,C_i+0.3\,T_i+0.2\,R_i$",
  "Skor tawaran CNP (Bab 4): C biaya ternormalisasi, T ketepatan waktu, R keandalan. Pemenang = skor tertinggi."),
 # ---------------- D. Carrier decision
 ("z", "D. Keputusan carrier (hibrida ML + DSS)", r"$z_j=100\left(w_c\,\dfrac{c_{\min}}{c_j}+w_t\,\dfrac{d_{\min}}{d_j}+w_r\,T_j\right)$",
  "Skor DSS carrier j: c_j biaya, d_j keberangkatan, T_j trust; w_c=0,45, w_t=0,25, w_r=0,30 (jumlah = 1). Benefit/cost dinormalisasi seperti Bab 3."),
 ("hybrid", "D. Keputusan carrier (hibrida ML + DSS)", r"$h_j=g_j\left[\alpha\,z_j+(1-\alpha)\cdot 100\,(1-p_j)\right]$",
  "Skor hibrida (Bab 3): g_j gerbang kelayakan (1 bila trust >= 0,60 dan keberangkatan <= LSD), p_j probabilitas roll-over dari model ML, alpha = 0,55."),
 ("expcost", "D. Keputusan carrier (hibrida ML + DSS)", r"$E[\mathrm{cost}_j]=c_j+(1-p_j)\,\mathrm{Pen}_0+p_j\,\mathrm{Pen}_7$",
  "Biaya harapan: Pen_0 penalti bila kargo terangkut, Pen_7 bila tergeser 7 hari (roll-over). Dipakai Risk Agent untuk membandingkan dengan air freight."),
 ("trust", "D. Keputusan carrier (hibrida ML + DSS)", r"$T_j(t+1)=\lambda\,T_j(t)+(1-\lambda)\,q,\quad \lambda=0.8$",
  "Trust eksponensial (Bab 4): q = 1 bila kargo terangkut tepat waktu, 0,2 bila roll-over. Trusted >= 0,80; conditional 0,60-0,80; blocked < 0,60."),
 # ---------------- E. ML
 ("cos", "E. Machine learning", r"$\cos(\mathbf{a},\mathbf{b})=\dfrac{\mathbf{a}\cdot\mathbf{b}}{\|\mathbf{a}\|\,\|\mathbf{b}\|}$",
  "Kemiripan kosinus vektor TF-IDF deskripsi produk (Compliance Agent, klasifikasi HS) dan vektor teks lain."),
 ("tfidf", "E. Machine learning", r"$\mathrm{tfidf}(t,d)=\mathrm{tf}(t,d)\left(\ln\dfrac{1+N}{1+\mathrm{df}(t)}+1\right)$",
  "tf frekuensi term t pada dokumen d, N jumlah dokumen latih, df(t) jumlah dokumen yang memuat t (varian smooth scikit-learn); dipakai untuk n-gram kata dan karakter."),
 ("knn", "E. Machine learning", r"$\mathrm{conf}(y)=\dfrac{\sum_{i\in N_k,\ y_i=y}\cos(x,x_i)}{\sum_{i\in N_k}\cos(x,x_i)}$",
  "k-NN berbobot kosinus (k=5): confidence = porsi bobot tetangga N_k yang berlabel y. Bila conf < 0,60 keputusan diserahkan ke manusia (selective classification)."),
 ("logit", "E. Machine learning", r"$p=\sigma(z)=\dfrac{1}{1+e^{-z}},\qquad z=b+\mathbf{w}^{\top}\tilde{\mathbf{x}}$@@$\mathcal{L}=-\dfrac{1}{n}\sum_i\left[y_i\ln p_i+(1-y_i)\ln(1-p_i)\right]+\dfrac{\lambda}{2}\|\mathbf{w}\|^2,\qquad \mathbf{w}\leftarrow\mathbf{w}-\eta\,\nabla\mathcal{L}$",
  "Regresi logistik Risk Agent: x~ fitur terstandarisasi (carrier, kongesti, musim puncak, buffer hari, jumlah kontainer), y = 1 bila roll-over, lambda regularisasi L2, eta learning rate."),
 ("truth", "E. Machine learning", r"$\mathrm{logit}\,p_j=b_j+1.8\,\mathrm{cong}+1.1\,\mathrm{peak}-0.3\,\mathrm{buf}$",
  "Proses pembangkit data (kebenaran tersembunyi yang tidak dilihat agen): b_j dasar per carrier, cong indeks kongesti pelabuhan, peak musim puncak, buf selisih hari antara tiba di gerbang dan closing."),
 ("metrics", "E. Machine learning", r"$\mathrm{AUC}=P(s^{+}>s^{-}),\qquad \mathrm{Brier}=\dfrac{1}{n}\sum_i(p_i-y_i)^2$",
  "AUC peluang skor kasus positif melebihi negatif; Brier skor kalibrasi probabilitas (lebih kecil lebih baik)."),
 ("slope", "E. Machine learning", r"$\hat{\beta}=\dfrac{\sum_t (t-\bar t)(x_t-\bar x)}{\sum_t (t-\bar t)^2}$",
  "Kemiringan tren percept sequence sensor mesin (Bab 2: 55, 60, 64, 72, 80 derajat C). Tren naik = sinyal risiko kerusakan sebelum gagal."),
 # ---------------- F. RL
 ("q", "F. Reinforcement learning", r"$Q(s,a)\leftarrow Q(s,a)+\alpha\left[r+\gamma\max_{a'}Q(s',a')-Q(s,a)\right]$",
  "Q-learning (Bab 4-5): s = (bucket slack, bucket nilai order, tahap), a in {normal, lembur}, r = -biaya lembur; reward akhir = -penalti. alpha learning rate, gamma discount."),
 ("eps", "F. Reinforcement learning", r"$a=\begin{cases}\end{cases}$", ""),
 # ---------------- G. MAS
 ("nego", "G. Koordinasi dan negosiasi", r"$p_B(t)=p_B^{0}+\left(p_B^{\max}-p_B^{0}\right)\left(\dfrac{t}{T}\right)^{\beta}$",
  "Konsesi bergantung waktu (Bab 4): pembeli menaikkan tawaran dari p_B^0 menuju batas p_B^max dalam T ronde; beta mengatur kecepatan konsesi. Sepakat bila tawaran pembeli >= permintaan penjual."),
 ("nash", "G. Koordinasi dan negosiasi", r"$x^{*}=\arg\max_{x}\prod_{i}\left[U_i(x)-d_i\right]$",
  "Nash bargaining: memaksimalkan hasil kali keuntungan relatif tiap pihak terhadap utilitas bila gagal sepakat (d_i)."),
 ("speed", "G. Koordinasi dan negosiasi", r"$S(n)=\dfrac{T_1}{T_n},\quad \eta(n)=\dfrac{S(n)}{n},\qquad R_{\mathrm{sys}}=1-\prod_i(1-R_i)$",
  "Speedup dan efisiensi paralel; keandalan sistem dengan redundansi (3 agen R=0,9 memberi 0,999). Sumber: Bab 4 sub-bab Skalabilitas."),
 ("comm", "G. Koordinasi dan negosiasi", r"$C_{\mathrm{comm}}=\sum_m\left(\dfrac{L_m}{B}+\tau\right),\qquad \mathrm{Jain}(x)=\dfrac{(\sum x_i)^2}{n\sum x_i^2}$",
  "Biaya komunikasi: L ukuran pesan, B bandwidth 8 Mbps, tau latensi 20 ms. Indeks keadilan Jain untuk pemerataan utilisasi mesin (1 = merata)."),
 # ---------------- H. Security & mobility
 ("sec", "H. Keamanan, trust, dan mobilitas agen", r"$\sigma=\mathrm{HMAC}_{K}\left(H(m)\right),\qquad \mathrm{accept}\Leftrightarrow \mathrm{nonce}\notin\mathrm{Seen}\ \wedge\ |t_{\mathrm{now}}-t_m|<\Delta\ \wedge\ a\in\mathrm{Cap}_i$",
  "Integritas pesan (tanda tangan HMAC-SHA256), pertahanan replay (nonce + jendela waktu Delta), dan capability check (aksi harus ada pada himpunan wewenang agen)."),
 ("mig", "H. Keamanan, trust, dan mobilitas agen", r"$\mathrm{migrate}\Leftrightarrow T_{\mathrm{host}}\geq\theta_T\ \wedge\ \mathrm{Verify}(\sigma)\ \wedge\ \mathrm{Risk}\leq\theta_R$@@$\mathrm{Score}=0.5\,(1-\mathrm{lat}_{\mathrm{norm}})+0.5\,T_{\mathrm{host}}$",
  "Syarat migrasi Scout Agent (Bab 4-5): trust host >= 0,80, state terverifikasi, risiko <= 0,20. Skor komposit hanya meranking host yang lolos; keamanan adalah constraint keras."),
]
F = [f for f in F if f[0] != "eps"]
